name: Commit automático diário

on:
  schedule:
    - cron: '0 0 * * *' # Este cron job executa diariamente à meia-noite UTC

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Fazer alterações (substitua esta etapa conforme necessário)
        run: |
          echo "Atualização automática" >> auto_update.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Commit automático diário"

      - name: Push das alterações
        env:
          TOKEN: ${{ secrets.WORK_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.WORK_TOKEN }}@github.com/<ORGANIZACAO>/<REPOSITORIO>.git HEAD:main
