name: Commit automático diário

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite UTC

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Fazer alterações no README.md
        run: |
          echo "Atualização automática: $(date)" >> README.md

      - name: Commit e Push das alterações
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualização automática no README.md"
          file_pattern: README.md
          branch: main
          token: ${{ secrets.ORG }}
