name: Commit automático simples

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
    # - cron: '0 0 * * *' # Executa diariamente à meia-noite UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Fazer alterações no README.md com a data atual
        run: |
          echo "## Atualização automática em: $(date '+%Y-%m-%d %H:%M:%S')" >> README.md


      - name: Configurar git
        run: |
          git config user.name "felipemacedo1"
          git config user.email "felipealexandrej@gmail.com"

      - name: Commit e Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add README.md
          git commit -m "Atualização automática no README.md"
          git push https://$GITHUB_TOKEN@github.com/BliShem/CryptoTool.git main
