name: Commit automático simples

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
    # - cron: '0 0 * * *' # Executa diariamente à meia-noite UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Fazer alterações no README.md
        run: echo "## Atualização automática:" >> README.md

      - name: Configurar git
        run: |
          git config user.name "felipemacedo1"
          git config user.email "felipealexandrej@gmail.com"

      - name: Commit e Push
        env:
          PAT_TOKEN: ${{ secrets.WORK_TOKEN }}
        run: |
          git add README.md
          git commit -m "Atualização automática no README.md"
          git push https://$PAT_TOKEN@github.com/BliShem/CryptoTool.git main
